[package]
name = "win32"
version.workspace = true
edition.workspace = true

[[bin]]
name = "galleon_win32"
path = "src/main.rs"

[dependencies]
core.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
