[package]
name = "win32"
version.workspace = true
edition.workspace = true

[[bin]]
name = "galleon_win32"
path = "src/main.rs"

[dependencies]
common.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
